language: python

os:
  - linux

python:
  - "2.7"
  - "3.5"
  - "3.6"

install:
  - pip install numpy
  - pip install scipy
  - pip install -r requirements.txt
  - pip install .
  - pip install pytest pytest-cov coverage coveralls
  - pip install travis-sphinx

script:
  - pytest --cov seglearn

after_success:
  - coveralls
